services:
  canvas-notebook:
    build: .
    ports:
      - "3456:3000"
    env_file:
      - .env.docker.local
    environment:
      # Do not change
      HOSTNAME: 0.0.0.0
      DATA: /data
      ALLOW_SIGNUP: "false"

      # Logging level: off | error | warn | info | debug (default: info)
      LOG_LEVEL: "info"

    volumes:
      - ./data:/data
    restart: unless-stopped
