import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Templates are references, not runtime source code.
    "docs/template/**",
    // Generated OAuth flow files
    "data/pi-oauth-states/**",
    // Skill templates and generated files
    "data/skills/**",
    "skills/**",
    // Temporary files generated by skills
    "data/temp/**",
    // Workspace files
    "data/workspace/**",
    // Compiled JavaScript files (TypeScript source exists)
    "server/*.js",
    "scripts/*.js",
  ]),
]);

export default eslintConfig;
