export const DIRECT_MCP_OAUTH_FAILURE_CODES = [
  'OAUTH_REFRESH_REVOKED',
  'OAUTH_REFRESH_EXPIRED',
  'OAUTH_REFRESH_SESSION_INACTIVE',
  'OAUTH_REFRESH_USER_BLOCKED',
  'OAUTH_REFRESH_CLIENT_DISABLED',
  'OAUTH_REFRESH_SEAT_DENIED',
  'OAUTH_RESOURCE_MISSING',
  'OAUTH_RESOURCE_INVALID',
  'OAUTH_TOKEN_INVALID_GRANT',
  'OAUTH_TOKEN_INVALID_CLIENT',
  'OAUTH_TOKEN_INVALID_SCOPE',
  'OAUTH_TOKEN_INVALID_TARGET',
] as const;

export type DirectMcpOAuthFailureCode = typeof DIRECT_MCP_OAUTH_FAILURE_CODES[number];
