import type * as YTypes from 'yjs';

import { Y } from './server-runtime';

// Persistence previously had no whole-state binary ceiling. Bound this pure
// decoder at 64 MiB (eight times the maximum proposal candidate) so accumulated
// tombstone history has headroom without allowing unbounded scratch documents.
// This is deliberately not the 1 MiB per-message transport limit.
const MAX_PERSISTENCE_UPDATE_BYTES = 64 * 1024 * 1024;

export type CollaborationPersistenceMergeResult = {
  update: Uint8Array;
  stateVector: Uint8Array;
  disposition: 'unchanged' | 'advanced' | 'merged';
  incomingNeedsReconcile: boolean;
};

type CompleteUpdate = {
  doc: YTypes.Doc;
  snapshot: YTypes.Snapshot;
  stateVector: Uint8Array;
  update: Uint8Array;
};

function assertBoundedUpdate(label: string, update: Uint8Array, maxBytes = MAX_PERSISTENCE_UPDATE_BYTES): void {
  if (!(update instanceof Uint8Array)) throw new TypeError(`${label} must be a Uint8Array.`);
  if (update.byteLength === 0) throw new Error(`${label} must not be an empty binary payload.`);
  if (update.byteLength > maxBytes) {
    throw new RangeError(`${label} exceeds the ${Math.floor(MAX_PERSISTENCE_UPDATE_BYTES / 1024 / 1024)} MiB persistence update limit.`);
  }
}

function sameBytes(left: Uint8Array, right: Uint8Array): boolean {
  return left.byteLength === right.byteLength && left.every((byte, index) => byte === right[index]);
}

function decodeCompleteUpdate(
  label: string,
  source: Uint8Array,
  maxBytes = MAX_PERSISTENCE_UPDATE_BYTES,
  requireCanonical = true,
): CompleteUpdate {
  assertBoundedUpdate(label, source, maxBytes);
  // Capture before invoking Yjs so callers retain immutable input buffers even
  // if a future runtime changes decoder or merge implementation details.
  // Buffer is a Uint8Array subclass, but Buffer.slice() aliases its source.
  const update = new Uint8Array(source);
  const doc = new Y.Doc({ gc: false });
  try {
    Y.applyUpdate(doc, update);
  } catch (cause) {
    doc.destroy();
    throw new Error(`${label} is not a valid Yjs V1 update.`, { cause });
  }
  if (doc.store.pendingStructs || doc.store.pendingDs) {
    doc.destroy();
    throw new Error(`${label} is not a complete, self-contained Yjs V1 update.`);
  }
  // Yjs accepts trailing bytes. Persistence accepts only the exact canonical
  // full-state encoding so corruption cannot hide behind a readable prefix.
  if (requireCanonical && !sameBytes(Y.encodeStateAsUpdate(doc), update)) {
    doc.destroy();
    throw new Error(`${label} is not a canonical full Yjs V1 update.`);
  }
  return {
    doc,
    snapshot: Y.snapshot(doc),
    stateVector: Y.encodeStateVector(doc),
    update,
  };
}

/**
 * Checks causal containment using both Yjs clocks and delete ranges. A state
 * vector alone cannot distinguish deletion-only changes.
 *
 * This relies on Yjs's immutable struct identity contract: one (client, clock)
 * identifies one struct payload forever. Snapshots intentionally do not hash
 * struct values, so this helper is not an authenticity check for adversarial
 * updates that reuse an existing identity with different content. Callers must
 * supply updates generated by conforming Yjs peers from a trusted document
 * lineage.
 */
function snapshotContains(covering: YTypes.Snapshot, required: YTypes.Snapshot): boolean {
  for (const [clientId, requiredClock] of required.sv) {
    if ((covering.sv.get(clientId) ?? 0) < requiredClock) return false;
  }
  return Y.equalDeleteSets(
    covering.ds,
    Y.mergeDeleteSets([covering.ds, required.ds]),
  );
}

/**
 * Produces a monotonic full-state update without database or domain policy.
 * Ancestors are no-ops, descendants advance directly, and divergent complete
 * updates become a canonical gc:false union so neither valid branch is lost.
 */
export function mergeCollaborationPersistenceUpdates(
  current: Uint8Array,
  incoming: Uint8Array,
): CollaborationPersistenceMergeResult {
  const currentState = decodeCompleteUpdate('Current persistence update', current);
  let incomingState: CompleteUpdate | undefined;
  let mergedState: CompleteUpdate | undefined;
  try {
    incomingState = decodeCompleteUpdate('Incoming persistence update', incoming);
    const currentContainsIncoming = snapshotContains(currentState.snapshot, incomingState.snapshot);
    const incomingContainsCurrent = snapshotContains(incomingState.snapshot, currentState.snapshot);

    if (currentContainsIncoming) {
      return {
        update: currentState.update.slice(),
        stateVector: currentState.stateVector.slice(),
        disposition: 'unchanged',
        incomingNeedsReconcile: !incomingContainsCurrent,
      };
    }
    if (incomingContainsCurrent) {
      return {
        update: incomingState.update.slice(),
        stateVector: incomingState.stateVector.slice(),
        disposition: 'advanced',
        incomingNeedsReconcile: false,
      };
    }

    let mergedUpdate: Uint8Array;
    try {
      mergedUpdate = Y.mergeUpdates([currentState.update, incomingState.update]);
    } catch (cause) {
      throw new Error('The complete Yjs persistence updates could not be merged.', { cause });
    }
    // Two individually bounded sources cap the temporary union at 128 MiB. The
    // canonical persisted result must still satisfy the normal 64 MiB limit.
    mergedState = decodeCompleteUpdate(
      'Merged persistence update',
      mergedUpdate,
      MAX_PERSISTENCE_UPDATE_BYTES * 2,
      false,
    );
    const canonicalUpdate = Y.encodeStateAsUpdate(mergedState.doc);
    assertBoundedUpdate('Canonical merged persistence update', canonicalUpdate);
    if (!snapshotContains(mergedState.snapshot, currentState.snapshot)
      || !snapshotContains(mergedState.snapshot, incomingState.snapshot)) {
      throw new Error('The merged Yjs persistence update does not contain both source snapshots.');
    }
    return {
      update: canonicalUpdate.slice(),
      stateVector: Y.encodeStateVector(mergedState.doc),
      disposition: 'merged',
      incomingNeedsReconcile: true,
    };
  } finally {
    mergedState?.doc.destroy();
    incomingState?.doc.destroy();
    currentState.doc.destroy();
  }
}
