import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const read = (relativePath: string) => readFileSync(path.join(root, relativePath), 'utf8');

const navigation = read('app/components/settings/SettingsNavigation.tsx');
const settingsClient = read('app/components/settings/IntegrationsSettingsClient.tsx');
const agentSettings = read('app/components/settings/AgentSettingsPanel.tsx');
const runtimeCard = read('app/components/settings/AgentRuntimePreferenceCard.tsx');
const modelOverrideCard = read('app/components/settings/AgentCatalogModelOverrideEditor.tsx');
const chatComposer = read('app/components/canvas-agent-chat/ChatComposer.tsx');
const chatModelSelector = read('app/components/canvas-agent-chat/ChatModelSelector.tsx');
const grantClient = read('app/lib/agent-runtime-policy/user-credential-grants-client.ts');
const onboardingWizard = read('app/[locale]/(routes)/onboarding/onboarding-wizard.tsx');
const providerPanel = read('app/components/settings/AiProvidersModelsPanel.tsx');
const providerCard = read('app/components/settings/ai-runtime/AiProviderCatalogCard.tsx');
const providerDialog = read('app/components/settings/ai-runtime/AiProviderEditorDialog.tsx');
const providerCredentialEditor = read('app/components/settings/ProviderInstallationCredentialEditor.tsx');
const providerEnvEditor = read('app/components/settings/ProviderEnvEditor.tsx');
const providerHelp = read('app/lib/pi/provider-help.ts');
const messagesDe = read('messages/de.json');
const messagesEn = read('messages/en.json');
const legacyRuntimePanelPath = path.join(root, 'app/components/settings/MyAgentRuntimePanel.tsx');

assert.doesNotMatch(navigation, /value:\s*['"]my-agent-runtime['"]/u);
assert.doesNotMatch(navigation, /\|\s*['"]my-agent-runtime['"]/u);
assert.match(settingsClient, /value === ['"]my-agent-runtime['"]\) return ['"]agent-settings['"]/u);
assert.doesNotMatch(settingsClient, /renderLazyTabContent\(['"]my-agent-runtime['"]/u);
assert.doesNotMatch(settingsClient, /import\(['"]@\/app\/components\/settings\/MyAgentRuntimePanel['"]\)/u);
assert.match(agentSettings, /<AgentRuntimePreferenceCard/u);
assert.match(agentSettings, /checked=\{modelOverrideEnabled\}/u);
assert.match(agentSettings, /!isMainAgent && selectedAgent && modelOverrideEnabled/u);
assert.match(agentSettings, /defaultProviderInstallationId:\s*null[\s\S]+defaultThinking:\s*null/u);
assert.doesNotMatch(modelOverrideCard, /<Switch/u);
assert.match(agentSettings, /searchParams\.get\(['"]tab['"]\) === ['"]my-agent-runtime['"] \? ['"]runtime['"] : null/u);
assert.match(runtimeCard, /data-testid="agent-runtime-provider"/u);
assert.match(runtimeCard, /data-testid="agent-runtime-model"/u);
assert.match(runtimeCard, /data-testid="agent-runtime-thinking"/u);
assert.match(runtimeCard, /enableInteractiveUserCredentialGrant/u);
assert.match(runtimeCard, /userCredentialEligibility\?\.consentGranted/u);
assert.match(chatModelSelector, /data-testid="chat-personal-provider-dialog"/u);
assert.match(chatModelSelector, /data-testid="chat-personal-provider-grant"/u);
assert.match(chatModelSelector, /supportsPersonalProviderActivation/u);
assert.match(chatModelSelector, /activeProviderId=\{personalProvider\.providerId\}/u);
assert.match(grantClient, /allowedExecutionModes:\s*\['interactive'\]/u);
assert.match(grantClient, /expectedRevision:\s*currentPayload\.data\?\.grant\?\.revision \?\? 0/u);
assert.match(chatComposer, /href="\/settings\?tab=agent-settings&panel=runtime"/u);
assert.doesNotMatch(chatComposer, /tab=my-agent-runtime/u);
assert.doesNotMatch(onboardingWizard, /PersonalRuntimeStep/u);
assert.doesNotMatch(onboardingWizard, /step === ['"]runtime['"]/u);
assert.doesNotMatch(onboardingWizard, /MyAgentRuntimePanel/u);
assert.match(onboardingWizard, /USER_STEPS[^\n]+\['language', 'workspace', 'profile', 'tour', 'done'\]/u);
assert.match(onboardingWizard, /presentation="onboarding"/u);
assert.match(onboardingWizard, /onOnboardingStateChange/u);
assert.doesNotMatch(onboardingWizard, /AiProviderCredentialsPanel/u);
assert.equal(existsSync(legacyRuntimePanelPath), false);

assert.match(providerPanel, /data-testid="chat-default-card"[\s\S]+aria-labelledby="provider-overview-heading"/u);
assert.match(providerPanel, /data-testid="onboarding-provider-panel"/u);
assert.match(providerPanel, /presentation === ['"]onboarding['"]/u);
assert.match(providerPanel, /verificationOnly/u);
assert.match(providerPanel, /<AiProviderEditorDialog/u);
assert.match(providerPanel, /enabled:\s*false/u);
assert.match(providerPanel, /modelIds:\s*\[\]/u);
assert.doesNotMatch(providerPanel, /ollamaCustomModel:\s*['"]llama3\.1['"]/u);
assert.match(providerCard, /data-testid=\{`provider-summary-/u);
assert.match(providerDialog, /data-testid="provider-editor-dialog"/u);
assert.match(providerDialog, /data-testid="provider-dialog-provider-select"/u);
assert.match(providerDialog, /value=\{providerSelectionConfirmed \? draft\.providerId : ''\}/u);
assert.match(providerDialog, /showConfiguration = !isNew \|\| providerSelectionConfirmed/u);
assert.match(providerDialog, /\{showConfiguration && <section/u);
assert.match(providerDialog, /!isNew \|\| connectionStepConfirmed/u);
assert.match(providerDialog, /copy\.continueToModels/u);
assert.match(providerDialog, /data-testid="ollama-server-url"/u);
assert.match(providerDialog, /data-testid="ollama-discover-models"/u);
assert.match(providerDialog, /data-testid="provider-custom-model-input"/u);
assert.match(providerDialog, /data-testid="provider-save"/u);
assert.match(providerDialog, /data-testid="provider-save-verify"/u);
assert.match(providerDialog, /data-testid="provider-save-verify-use"/u);
assert.match(providerDialog, /credentialEditorRef\.current\?\.save/u);
assert.match(providerCredentialEditor, /showCredentialActions/u);
assert.match(providerEnvEditor, /useImperativeHandle/u);
assert.match(providerEnvEditor, /showActions &&/u);
assert.match(providerDialog, /ollamaAdditionalModels/u);
assert.match(providerDialog, /\/api\/admin\/agent-runtime\/providers\/ollama\/discover/u);
assert.match(providerHelp, /name:\s*['"]OLLAMA_API_KEY['"][\s\S]+required:\s*false/u);
assert.doesNotMatch(messagesDe, /zufällige Zahlenkette/u);
assert.doesNotMatch(messagesEn, /random numeric fallback/u);

console.log('agent-runtime-settings-ui-test: ok');
