import assert from 'node:assert/strict';
import { legacyPluginSettingsHref, readPluginNavigation, updatePluginNavigation } from '../app/lib/plugins/plugin-navigation';

assert.deepEqual(readPluginNavigation(new URLSearchParams()), { area: 'plugins', view: 'discover', scope: 'user' });
assert.deepEqual(readPluginNavigation(new URLSearchParams('area=skills&view=library&scope=organization')), { area: 'skills', view: 'library', scope: 'organization' });
assert.equal(readPluginNavigation(new URLSearchParams('area=skills&view=advanced')).view, 'installed');
assert.equal(readPluginNavigation(new URLSearchParams('view=library&scope=system')).view, 'discover');
assert.equal(readPluginNavigation(new URLSearchParams('scope=system')).scope, 'user');
assert.equal(updatePluginNavigation('view=advanced&q=mail', { area: 'skills' }), '/plugins?q=mail&area=skills&view=installed');
assert.equal(updatePluginNavigation('area=skills&view=library&scope=organization', { area: 'plugins' }), '/plugins?scope=organization&view=discover');
assert.equal(updatePluginNavigation('view=updates&scope=organization', { scope: 'user' }), '/plugins?view=updates');
assert.equal(legacyPluginSettingsHref({ tab: 'plugins' }), '/plugins?view=discover');
assert.equal(legacyPluginSettingsHref({ tab: ['skills'], view: 'library', scope: 'organization' }), '/plugins?view=library&scope=organization&area=skills');
assert.equal(legacyPluginSettingsHref({ tab: 'general' }), null);
assert.equal(legacyPluginSettingsHref({ tab: 'plugins', q: 'mail & calendar' }), '/plugins?q=mail+%26+calendar&view=discover');
const filtered = readPluginNavigation(new URLSearchParams('view=discover&q=team&page=3&category=Work&connection=mcp'));
assert.equal(filtered.q, 'team');
assert.equal(filtered.page, 3);
assert.equal(filtered.category, 'Work');
assert.equal(filtered.connection, 'mcp');
assert.equal(readPluginNavigation(new URLSearchParams('page=3junk&connection=invalid&readiness=invalid&enabled=all')).page, undefined);
assert.equal(readPluginNavigation(new URLSearchParams('page=100001')).page, undefined);
const resetPage = new URL(updatePluginNavigation('view=discover&q=team&page=3&category=Work', { connection: 'mcp' }), 'https://canvas.test');
assert.equal(resetPage.searchParams.has('page'), false, 'filter changes reset pagination');
assert.equal(resetPage.searchParams.get('q'), 'team');
const resetScope = new URL(updatePluginNavigation('view=installed&q=team&page=3&readiness=available&enabled=enabled', { scope: 'organization' }), 'https://canvas.test');
assert.equal(resetScope.searchParams.get('scope'), 'organization');
for (const key of ['q', 'page', 'readiness', 'enabled']) assert.equal(resetScope.searchParams.has(key), false);
const installedView = new URL(updatePluginNavigation('view=discover&q=team&page=3&category=Work&connection=mcp', { view: 'installed' }), 'https://canvas.test');
assert.equal(installedView.searchParams.get('q'), 'team');
for (const key of ['page', 'category', 'connection']) assert.equal(installedView.searchParams.has(key), false);
const detailHref = new URL(updatePluginNavigation('view=discover&q=team&page=3&category=Work&connection=mcp', { plugin: 'team-plugin', source: 'store' }), 'https://canvas.test');
assert.equal(detailHref.searchParams.get('page'), '3', 'opening a detail preserves list position');
assert.equal(detailHref.searchParams.get('connection'), 'mcp');
console.log('Plugin navigation: explicit views, area defaults, legacy links, scope validation and query preservation passed');
