import { Type } from 'typebox';
import { Value } from 'typebox/value';
import { ProposalToolEditSchemaV1, parseProposalToolEditV1 } from '../file-version-center/contracts/proposal-tools-v1';

const blockId = Type.String({ minLength: 1, description: 'Stable block ID from read(includeStructure: true).' });
const parentId = Type.Union([blockId, Type.Null()], { description: 'Parent block ID, or null for the document root.' });
const beforeId = Type.Union([blockId, Type.Null()], { description: 'Next sibling block ID, or null to append to this parent.' });
const fingerprint = Type.String({ pattern: '^[a-f0-9]{64}$', description: 'Exact hash returned by the current structure read.' });

const documentReference = Type.Object({
  documentId: Type.String({ minLength: 1 }),
  lifecycleGeneration: Type.Integer({ minimum: 1 }),
  schemaVersion: Type.Integer({ minimum: 1 }),
}, { additionalProperties: false, description: 'Copy document from the current read metadata; identifies the document lifecycle and schema.' });

const editableAttribute = Type.Union([
  Type.Object({ level: Type.Integer({ minimum: 1, maximum: 6 }) }, { additionalProperties: false }),
  Type.Object({ checked: Type.Boolean() }, { additionalProperties: false }),
  Type.Object({ start: Type.Integer({ minimum: 1, maximum: Number.MAX_SAFE_INTEGER }) }, { additionalProperties: false }),
  Type.Object({ language: Type.Union([Type.String({ maxLength: 64, pattern: '^[\\w+-]*$' }), Type.Null()]) }, { additionalProperties: false }),
], { description: 'Exactly one attribute: heading level, taskItem checked, orderedList start, or codeBlock language. beforeAttrs and afterAttrs must name the same attribute.' });

const insertedBlock = Type.Object({
  type: Type.String({ minLength: 1, description: 'ProseMirror block node type, for example paragraph, heading, bulletList, or table.' }),
  attrs: Type.Optional(Type.Record(Type.String(), Type.Unknown())),
  content: Type.Optional(Type.Array(Type.Unknown(), {
    description: 'Nested ProseMirror JSONContent nodes: type, optional attrs/content/marks/text. All nested nodes and attributes are validated against the editor schema at runtime.',
  })),
}, {
  additionalProperties: false,
  description: 'ProseMirror JSONContent for a new block. IDs are generated by the server; supplied attrs.id values are discarded recursively. Maximum 256 new blocks and 512 KiB per request, checked at runtime.',
});

const structuredOperation = Type.Union([
  Type.Object({
    kind: Type.Literal('move_block'), blockId, placementHash: fingerprint, parentId, beforeId,
  }, { additionalProperties: false, description: 'Move an existing block using its placementHash; unrelated text edits do not invalidate this condition.' }),
  Type.Object({
    kind: Type.Literal('delete_block'), blockId, subtreeHash: fingerprint,
  }, { additionalProperties: false, description: 'Delete this block and its descendants only if its subtree still matches the read.' }),
  Type.Object({
    kind: Type.Literal('insert_blocks'), parentId, beforeId, blocks: Type.Array(insertedBlock, { minItems: 1, maxItems: 256 }),
  }, { additionalProperties: false, description: 'Insert new blocks at a stable parent and next-sibling anchor.' }),
  Type.Object({
    kind: Type.Literal('format_block'), blockId, beforeAttrs: editableAttribute, afterAttrs: editableAttribute,
  }, {
    additionalProperties: false, description: 'Change one supported block attribute, requiring its exact current value in beforeAttrs.',
    anyOf: ['level', 'checked', 'start', 'language'].map((attribute) => ({
      properties: { beforeAttrs: { required: [attribute] }, afterAttrs: { required: [attribute] } },
    })),
  }),
  Type.Object({
    kind: Type.Literal('format_text'), blockId, subtreeHash: fingerprint,
    from: Type.Integer({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER }),
    to: Type.Integer({ minimum: 1, maximum: Number.MAX_SAFE_INTEGER }),
    mark: Type.Union([Type.Literal('bold'), Type.Literal('italic'), Type.Literal('strike'), Type.Literal('code'), Type.Literal('link')]),
    enabled: Type.Boolean(),
    href: Type.Optional(Type.String({ minLength: 1, maxLength: 2048, description: 'Required only when enabling a link. The editor validates the URL.' })),
  }, {
    additionalProperties: false,
    description: 'Add or remove an inline mark in one text block. from/to are UTF-16 ProseMirror content offsets within the block, with from < to. The runtime validates text and grapheme boundaries and the block subtreeHash.',
    anyOf: [
      { properties: { mark: { const: 'link' }, enabled: { const: true } }, required: ['href'] },
      { properties: { enabled: { const: false } }, not: { required: ['href'] } },
      { properties: { mark: { not: { const: 'link' } } }, not: { required: ['href'] } },
    ],
  }),
  Type.Object({
    kind: Type.Literal('table_operation'), cellId: blockId, subtreeHash: fingerprint,
    action: Type.Union([
      Type.Literal('addRowBefore'), Type.Literal('addRowAfter'), Type.Literal('deleteRow'),
      Type.Literal('addColumnBefore'), Type.Literal('addColumnAfter'), Type.Literal('deleteColumn'),
      Type.Literal('deleteTable'), Type.Literal('alignLeft'), Type.Literal('alignCenter'),
      Type.Literal('alignRight'), Type.Literal('alignNone'), Type.Literal('moveRowUp'),
      Type.Literal('moveRowDown'), Type.Literal('moveColumnLeft'), Type.Literal('moveColumnRight'),
    ]),
  }, { additionalProperties: false, description: 'Apply an editor table command at cellId; use the containing table block\'s subtreeHash.' }),
]);

// Keep an object at the schema root for tool providers and parameter discovery.
// The alternatives require exactly one public edit form, including its local guards.
export const agentEditFileParameters = Type.Object({
  path: Type.String({ description: 'Absolute path or workspace-relative path.' }),
  proposal: Type.Optional(ProposalToolEditSchemaV1),
  mode: Type.Optional(Type.Union([
    Type.Literal('append'), Type.Literal('replace'), Type.Literal('insert_after_heading'),
  ], { description: 'Markdown-aware edit mode. Use only for .md, .markdown, or .mdx files.' })),
  content: Type.Optional(Type.String({ minLength: 1, description: 'Markdown fragment to append, insert, or use as the replacement.' })),
  heading: Type.Optional(Type.String({ minLength: 1, description: 'Exact heading title, with or without leading # markers, for insert_after_heading.' })),
  oldText: Type.Optional(Type.String({ description: 'Exact text to replace. Must occur exactly once by default, match expectedOccurrences, or use replaceAll.' })),
  newText: Type.Optional(Type.String({ description: 'Replacement text.' })),
  expectedOccurrences: Type.Optional(Type.Integer({ minimum: 1, description: 'Exact number of expected oldText matches. Defaults to 1.' })),
  replaceAll: Type.Optional(Type.Boolean({ description: 'Replace every matching non-overlapping occurrence. Cannot be true with expectedOccurrences.' })),
  expectedSha256: Type.Optional(Type.String({ description: 'Required for ordinary exact edits of shared files. Optional additional whole-document guard for structured or block-targeted edits; their local guards allow unrelated user edits.' })),
  blockId: Type.Optional(blockId),
  document: Type.Optional(documentReference),
  operations: Type.Optional(Type.Array(structuredOperation, { minItems: 1, maxItems: 32,
    description: 'Structured block edits for a tiptap_blocks live document. Use instead of oldText/newText and include document from a structure read.' })),
}, {
  additionalProperties: false,
  anyOf: [
    { required: ['oldText', 'newText'], not: { anyOf:
      ['operations', 'blockId', 'document', 'mode', 'content', 'heading'].map((key) => ({ required: [key] })) } },
    { required: ['oldText', 'newText', 'blockId', 'document'], not: { anyOf:
      ['operations', 'mode', 'content', 'heading'].map((key) => ({ required: [key] })) } },
    { required: ['operations', 'document'], not: { anyOf:
      ['oldText', 'newText', 'blockId', 'expectedOccurrences', 'replaceAll', 'mode', 'content', 'heading'].map((key) => ({ required: [key] })) } },
    { properties: { mode: { const: 'append' } }, required: ['mode', 'content'], not: { anyOf:
      ['oldText', 'newText', 'heading', 'operations', 'blockId', 'document', 'expectedOccurrences', 'replaceAll'].map((key) => ({ required: [key] })) } },
    { properties: { mode: { const: 'replace' } }, required: ['mode', 'content', 'oldText'], not: { anyOf:
      ['newText', 'heading', 'operations', 'blockId', 'document'].map((key) => ({ required: [key] })) } },
    { properties: { mode: { const: 'insert_after_heading' } }, required: ['mode', 'content', 'heading'], not: { anyOf:
      ['oldText', 'newText', 'operations', 'blockId', 'document', 'expectedOccurrences', 'replaceAll'].map((key) => ({ required: [key] })) } },
  ],
});

const editModes = ['append', 'replace', 'insert_after_heading'] as const;
const operationKinds = ['move_block', 'delete_block', 'insert_blocks', 'format_block', 'format_text', 'table_operation'] as const;
const tableActions = [
  'addRowBefore', 'addRowAfter', 'deleteRow', 'addColumnBefore', 'addColumnAfter', 'deleteColumn',
  'deleteTable', 'alignLeft', 'alignCenter', 'alignRight', 'alignNone', 'moveRowUp', 'moveRowDown',
  'moveColumnLeft', 'moveColumnRight',
] as const;
const textMarks = ['bold', 'italic', 'strike', 'code', 'link'] as const;
const hashExample = '0'.repeat(64);
const documentExample = { documentId: 'document-id', lifecycleGeneration: 1, schemaVersion: 1 };
const operationExamples: Record<(typeof operationKinds)[number], Record<string, unknown>> = {
  move_block: { kind: 'move_block', blockId: 'block-id', placementHash: hashExample, parentId: null, beforeId: null },
  delete_block: { kind: 'delete_block', blockId: 'block-id', subtreeHash: hashExample },
  insert_blocks: { kind: 'insert_blocks', parentId: null, beforeId: null,
    blocks: [{ type: 'paragraph', content: [{ type: 'text', text: 'New paragraph' }] }] },
  format_block: { kind: 'format_block', blockId: 'heading-id', beforeAttrs: { level: 1 }, afterAttrs: { level: 2 } },
  format_text: { kind: 'format_text', blockId: 'paragraph-id', subtreeHash: hashExample,
    from: 0, to: 4, mark: 'bold', enabled: true },
  table_operation: { kind: 'table_operation', cellId: 'cell-id', subtreeHash: hashExample, action: 'addRowAfter' },
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === 'object' && !Array.isArray(value));
}

function owns(value: Record<string, unknown>, key: string): boolean {
  return Object.hasOwn(value, key);
}

function withExample(message: string, example: Record<string, unknown>): string {
  return `${message} Example: ${JSON.stringify(example)}`;
}

function documentValidationError(value: unknown): string | null {
  const example = { path: 'document.md', document: documentExample, operations: [operationExamples.move_block] };
  if (!isRecord(value)) return withExample('Invalid edit_file arguments: document must be an object copied from read(source: "blocks").', example);
  const unexpected = Object.keys(value).find((key) => !['documentId', 'lifecycleGeneration', 'schemaVersion'].includes(key));
  if (unexpected) return withExample(`Invalid edit_file arguments: document.${unexpected} is not allowed. Allowed fields: documentId, lifecycleGeneration, schemaVersion.`, example);
  if (typeof value.documentId !== 'string' || value.documentId.length === 0) {
    return withExample('Invalid edit_file arguments: document.documentId is required and must be a non-empty string.', example);
  }
  for (const field of ['lifecycleGeneration', 'schemaVersion'] as const) {
    if (!Number.isInteger(value[field]) || Number(value[field]) < 1) {
      return withExample(`Invalid edit_file arguments: document.${field} is required and must be an integer of at least 1.`, example);
    }
  }
  return null;
}

function operationValidationError(value: unknown, index: number): string | null {
  const scope = `operations[${index}]`;
  if (!isRecord(value)) {
    return withExample(`Invalid edit_file arguments: ${scope} must be an operation object. Allowed kinds: ${operationKinds.join(', ')}.`, operationExamples.move_block);
  }
  if (typeof value.kind !== 'string' || !operationKinds.includes(value.kind as (typeof operationKinds)[number])) {
    return withExample(`Invalid edit_file arguments: ${scope}.kind is required and must be one of: ${operationKinds.join(', ')}.`, operationExamples.move_block);
  }
  const kind = value.kind as (typeof operationKinds)[number];
  const example = operationExamples[kind];
  const fields: Record<typeof kind, readonly string[]> = {
    move_block: ['kind', 'blockId', 'placementHash', 'parentId', 'beforeId'],
    delete_block: ['kind', 'blockId', 'subtreeHash'],
    insert_blocks: ['kind', 'parentId', 'beforeId', 'blocks'],
    format_block: ['kind', 'blockId', 'beforeAttrs', 'afterAttrs'],
    format_text: ['kind', 'blockId', 'subtreeHash', 'from', 'to', 'mark', 'enabled', 'href'],
    table_operation: ['kind', 'cellId', 'subtreeHash', 'action'],
  };
  const unexpected = Object.keys(value).find((key) => !fields[kind].includes(key));
  if (unexpected) {
    return withExample(`Invalid edit_file arguments: ${scope}.${unexpected} is not allowed for ${kind}. Allowed fields: ${fields[kind].join(', ')}.`, example);
  }
  const requireId = (field: string): string | null => typeof value[field] === 'string' && value[field].length > 0
    ? null : `${scope}.${field} is required and must be a non-empty block ID`;
  const requireHash = (field: string): string | null => typeof value[field] === 'string' && /^[a-f0-9]{64}$/u.test(value[field])
    ? null : `${scope}.${field} is required and must be the 64-character hash from read(source: "blocks")`;
  const requirePointer = (field: string): string | null => value[field] === null || (typeof value[field] === 'string' && value[field].length > 0)
    ? null : `${scope}.${field} is required and must be a block ID or null`;
  let problem: string | null = null;
  if (kind === 'move_block') {
    problem = requireId('blockId') || requireHash('placementHash') || requirePointer('parentId') || requirePointer('beforeId');
  } else if (kind === 'delete_block') {
    problem = requireId('blockId') || requireHash('subtreeHash');
  } else if (kind === 'insert_blocks') {
    problem = requirePointer('parentId') || requirePointer('beforeId');
    if (!problem && (!Array.isArray(value.blocks) || value.blocks.length < 1 || value.blocks.length > 256)) {
      problem = `${scope}.blocks is required and must contain 1–256 ProseMirror block objects`;
    }
    if (!problem && Array.isArray(value.blocks)) {
      const invalid = value.blocks.findIndex((block) => !isRecord(block) || typeof block.type !== 'string' || block.type.length === 0
        || Object.keys(block).some((key) => !['type', 'attrs', 'content'].includes(key))
        || (owns(block, 'attrs') && !isRecord(block.attrs)) || (owns(block, 'content') && !Array.isArray(block.content)));
      if (invalid >= 0) problem = `${scope}.blocks[${invalid}] must contain type and only optional attrs/content fields`;
    }
  } else if (kind === 'format_block') {
    problem = requireId('blockId');
    const allowed = ['level', 'checked', 'start', 'language'];
    if (!problem && (!isRecord(value.beforeAttrs) || Object.keys(value.beforeAttrs).length !== 1)) {
      problem = `${scope}.beforeAttrs must contain exactly one supported attribute: ${allowed.join(', ')}`;
    }
    if (!problem && (!isRecord(value.afterAttrs) || Object.keys(value.afterAttrs).length !== 1)) {
      problem = `${scope}.afterAttrs must contain exactly one supported attribute: ${allowed.join(', ')}`;
    }
    if (!problem && isRecord(value.beforeAttrs) && isRecord(value.afterAttrs)) {
      const beforeKey = Object.keys(value.beforeAttrs)[0]; const afterKey = Object.keys(value.afterAttrs)[0];
      if (!allowed.includes(beforeKey) || beforeKey !== afterKey) {
        problem = `${scope}.beforeAttrs and ${scope}.afterAttrs must name the same supported attribute: ${allowed.join(', ')}`;
      } else {
        const validAttribute = (key: string, attribute: unknown) => key === 'level'
          ? Number.isInteger(attribute) && Number(attribute) >= 1 && Number(attribute) <= 6
          : key === 'checked' ? typeof attribute === 'boolean'
            : key === 'start' ? Number.isSafeInteger(attribute) && Number(attribute) >= 1
              : attribute === null || (typeof attribute === 'string' && attribute.length <= 64 && /^[\w+-]*$/u.test(attribute));
        if (!validAttribute(beforeKey, value.beforeAttrs[beforeKey]) || !validAttribute(afterKey, value.afterAttrs[afterKey])) {
          problem = `${scope}.beforeAttrs and ${scope}.afterAttrs have an invalid ${beforeKey} value; level is 1–6, checked is boolean, start is at least 1, and language is null or a short language name`;
        }
      }
    }
  } else if (kind === 'format_text') {
    problem = requireId('blockId') || requireHash('subtreeHash');
    if (!problem && (!Number.isSafeInteger(value.from) || Number(value.from) < 0)) problem = `${scope}.from must be an integer of at least 0`;
    if (!problem && (!Number.isSafeInteger(value.to) || Number(value.to) < 1)) problem = `${scope}.to must be an integer of at least 1`;
    if (!problem && (typeof value.mark !== 'string' || !textMarks.includes(value.mark as (typeof textMarks)[number]))) {
      problem = `${scope}.mark must be one of: ${textMarks.join(', ')}`;
    }
    if (!problem && typeof value.enabled !== 'boolean') problem = `${scope}.enabled is required and must be boolean`;
    if (!problem && value.mark === 'link' && value.enabled === true
      && (typeof value.href !== 'string' || value.href.length === 0 || value.href.length > 2048)) {
      problem = `${scope}.href is required and must contain 1–2048 characters when enabling a link`;
    }
    if (!problem && !(value.mark === 'link' && value.enabled === true) && owns(value, 'href')) {
      problem = `${scope}.href is allowed only when enabling a link`;
    }
  } else if (kind === 'table_operation') {
    problem = requireId('cellId') || requireHash('subtreeHash');
    if (!problem && (typeof value.action !== 'string' || !tableActions.includes(value.action as (typeof tableActions)[number]))) {
      problem = `${scope}.action must be one of: ${tableActions.join(', ')}`;
    }
  }
  return problem ? withExample(`Invalid edit_file arguments: ${problem}.`, example) : null;
}

/** Produces one deterministic, actionable error instead of exposing every union-schema branch failure. */
export function formatAgentEditFileValidationError(value: unknown): string {
  if (!isRecord(value)) return 'Invalid edit_file arguments: expected an object. Example: {"path":"notes.md","mode":"append","content":"New text"}';
  if (typeof value.path !== 'string') return 'Invalid edit_file arguments: path is required and must be a string.';
  const rootFields = ['path', 'mode', 'content', 'heading', 'oldText', 'newText', 'expectedOccurrences', 'replaceAll',
    'expectedSha256', 'blockId', 'document', 'operations', 'proposal'];
  const unexpected = Object.keys(value).find((key) => !rootFields.includes(key));
  if (unexpected) return `Invalid edit_file arguments: ${unexpected} is not an allowed field. Allowed fields: ${rootFields.join(', ')}.`;
  if (owns(value, 'proposal')) {
    try { parseProposalToolEditV1(value.proposal); }
    catch (error) {
      return `Invalid edit_file arguments: proposal must be an explicit valid source from a proposal read. ${error instanceof Error ? error.message : 'Invalid proposal provenance.'} Read again; do not remove the reference to bypass the conflict.`;
    }
  }
  if (owns(value, 'expectedOccurrences') && (!Number.isInteger(value.expectedOccurrences) || Number(value.expectedOccurrences) < 1)) {
    return 'Invalid edit_file arguments: expectedOccurrences must be an integer of at least 1.';
  }
  if (owns(value, 'replaceAll') && typeof value.replaceAll !== 'boolean') {
    return 'Invalid edit_file arguments: replaceAll must be boolean.';
  }
  if (owns(value, 'expectedSha256') && typeof value.expectedSha256 !== 'string') {
    return 'Invalid edit_file arguments: expectedSha256 must be a string.';
  }

  if (owns(value, 'operations')) {
    const conflicts = ['mode', 'content', 'heading', 'oldText', 'newText', 'blockId', 'expectedOccurrences', 'replaceAll'].filter((key) => owns(value, key));
    if (conflicts.length) return `Invalid edit_file arguments: operations cannot be combined with ${conflicts.join(', ')}.`;
    const documentError = documentValidationError(value.document);
    if (documentError) return documentError;
    if (!Array.isArray(value.operations) || value.operations.length < 1 || value.operations.length > 32) {
      return withExample('Invalid edit_file arguments: operations must contain 1–32 operations.',
        { path: 'document.md', document: documentExample, operations: [operationExamples.move_block] });
    }
    for (let index = 0; index < value.operations.length; index++) {
      const error = operationValidationError(value.operations[index], index);
      if (error) return error;
    }
  } else if (owns(value, 'mode')) {
    if (typeof value.mode !== 'string' || !editModes.includes(value.mode as (typeof editModes)[number])) {
      return `Invalid edit_file arguments: mode must be one of: ${editModes.join(', ')}.`;
    }
    const commonConflicts = ['newText', 'operations', 'blockId', 'document'].filter((key) => owns(value, key));
    const modeConflicts = value.mode === 'append' ? ['oldText', 'heading', 'expectedOccurrences', 'replaceAll']
      : value.mode === 'replace' ? ['heading'] : ['oldText', 'heading', 'expectedOccurrences', 'replaceAll'].filter((key) => key !== 'heading');
    const conflicts = [...commonConflicts, ...modeConflicts.filter((key) => owns(value, key))];
    if (conflicts.length) return `Invalid edit_file arguments: mode ${value.mode} cannot be combined with ${conflicts.join(', ')}.`;
    if (typeof value.content !== 'string' || value.content.length === 0) {
      return `Invalid edit_file arguments: content is required and must be non-empty for mode ${value.mode}.`;
    }
    if (value.mode === 'replace' && typeof value.oldText !== 'string') {
      return 'Invalid edit_file arguments: oldText is required for mode replace. Example: {"path":"notes.md","mode":"replace","oldText":"Old","content":"New"}';
    }
    if (value.mode === 'insert_after_heading' && (typeof value.heading !== 'string' || value.heading.length === 0)) {
      return 'Invalid edit_file arguments: heading is required for mode insert_after_heading. Example: {"path":"notes.md","mode":"insert_after_heading","heading":"Details","content":"New section"}';
    }
  } else {
    const conflicts = ['content', 'heading'].filter((key) => owns(value, key));
    if (conflicts.length) return `Invalid edit_file arguments: an exact oldText/newText edit cannot include ${conflicts.join(', ')} without a Markdown mode.`;
    if (owns(value, 'document') && !owns(value, 'blockId')) {
      return 'Invalid edit_file arguments: document requires operations or blockId.';
    }
    if (owns(value, 'blockId') && !owns(value, 'document')) {
      return 'Invalid edit_file arguments: document is required when blockId targets a live block. Read source: "blocks" and copy its document reference.';
    }
    if (owns(value, 'blockId') && (typeof value.blockId !== 'string' || value.blockId.length === 0)) {
      return 'Invalid edit_file arguments: blockId must be a non-empty string copied from read(source: "blocks").';
    }
    if (typeof value.oldText !== 'string' || typeof value.newText !== 'string') {
      return 'Invalid edit_file arguments: supply oldText and newText for an exact edit, or choose a Markdown mode, or supply operations with document.';
    }
    if (owns(value, 'document')) {
      const documentError = documentValidationError(value.document);
      if (documentError) return documentError;
    }
  }

  const [error] = Array.from(Value.Errors(agentEditFileParameters, value));
  const location = error && 'path' in error && typeof error.path === 'string' && error.path ? error.path : '/';
  const message = error && 'message' in error ? String(error.message) : 'arguments do not match a supported edit form';
  return `Invalid edit_file arguments at ${location}: ${message}. Use exactly one edit form: exact text, Markdown mode, or structured operations.`;
}
