import { Type } from 'typebox';

const blockId = Type.String({ minLength: 1, description: 'Stable block ID from read(includeStructure: true).' });
const parentId = Type.Union([blockId, Type.Null()], { description: 'Parent block ID, or null for the document root.' });
const beforeId = Type.Union([blockId, Type.Null()], { description: 'Next sibling block ID, or null to append to this parent.' });
const fingerprint = Type.String({ pattern: '^[a-f0-9]{64}$', description: 'Exact hash returned by the current structure read.' });

const documentReference = Type.Object({
  documentId: Type.String({ minLength: 1 }),
  lifecycleGeneration: Type.Integer({ minimum: 1 }),
  schemaVersion: Type.Integer({ minimum: 1 }),
}, { additionalProperties: false, description: 'Copy document from the current read metadata; identifies the document lifecycle and schema.' });

const editableAttribute = Type.Union([
  Type.Object({ level: Type.Integer({ minimum: 1, maximum: 6 }) }, { additionalProperties: false }),
  Type.Object({ checked: Type.Boolean() }, { additionalProperties: false }),
  Type.Object({ start: Type.Integer({ minimum: 1, maximum: Number.MAX_SAFE_INTEGER }) }, { additionalProperties: false }),
  Type.Object({ language: Type.Union([Type.String({ maxLength: 64, pattern: '^[\\w+-]*$' }), Type.Null()]) }, { additionalProperties: false }),
], { description: 'Exactly one attribute: heading level, taskItem checked, orderedList start, or codeBlock language. beforeAttrs and afterAttrs must name the same attribute.' });

const insertedBlock = Type.Object({
  type: Type.String({ minLength: 1, description: 'ProseMirror block node type, for example paragraph, heading, bulletList, or table.' }),
  attrs: Type.Optional(Type.Record(Type.String(), Type.Unknown())),
  content: Type.Optional(Type.Array(Type.Unknown(), {
    description: 'Nested ProseMirror JSONContent nodes: type, optional attrs/content/marks/text. All nested nodes and attributes are validated against the editor schema at runtime.',
  })),
}, {
  additionalProperties: false,
  description: 'ProseMirror JSONContent for a new block. IDs are generated by the server; supplied attrs.id values are discarded recursively. Maximum 256 new blocks and 512 KiB per request, checked at runtime.',
});

const structuredOperation = Type.Union([
  Type.Object({
    kind: Type.Literal('move_block'), blockId, placementHash: fingerprint, parentId, beforeId,
  }, { additionalProperties: false, description: 'Move an existing block using its placementHash; unrelated text edits do not invalidate this condition.' }),
  Type.Object({
    kind: Type.Literal('delete_block'), blockId, subtreeHash: fingerprint,
  }, { additionalProperties: false, description: 'Delete this block and its descendants only if its subtree still matches the read.' }),
  Type.Object({
    kind: Type.Literal('insert_blocks'), parentId, beforeId, blocks: Type.Array(insertedBlock, { minItems: 1, maxItems: 256 }),
  }, { additionalProperties: false, description: 'Insert new blocks at a stable parent and next-sibling anchor.' }),
  Type.Object({
    kind: Type.Literal('format_block'), blockId, beforeAttrs: editableAttribute, afterAttrs: editableAttribute,
  }, {
    additionalProperties: false, description: 'Change one supported block attribute, requiring its exact current value in beforeAttrs.',
    anyOf: ['level', 'checked', 'start', 'language'].map((attribute) => ({
      properties: { beforeAttrs: { required: [attribute] }, afterAttrs: { required: [attribute] } },
    })),
  }),
  Type.Object({
    kind: Type.Literal('format_text'), blockId, subtreeHash: fingerprint,
    from: Type.Integer({ minimum: 0, maximum: Number.MAX_SAFE_INTEGER }),
    to: Type.Integer({ minimum: 1, maximum: Number.MAX_SAFE_INTEGER }),
    mark: Type.Union([Type.Literal('bold'), Type.Literal('italic'), Type.Literal('strike'), Type.Literal('code'), Type.Literal('link')]),
    enabled: Type.Boolean(),
    href: Type.Optional(Type.String({ minLength: 1, maxLength: 2048, description: 'Required only when enabling a link. The editor validates the URL.' })),
  }, {
    additionalProperties: false,
    description: 'Add or remove an inline mark in one text block. from/to are UTF-16 ProseMirror content offsets within the block, with from < to. The runtime validates text and grapheme boundaries and the block subtreeHash.',
    anyOf: [
      { properties: { mark: { const: 'link' }, enabled: { const: true } }, required: ['href'] },
      { properties: { enabled: { const: false } }, not: { required: ['href'] } },
      { properties: { mark: { not: { const: 'link' } } }, not: { required: ['href'] } },
    ],
  }),
  Type.Object({
    kind: Type.Literal('table_operation'), cellId: blockId, subtreeHash: fingerprint,
    action: Type.Union([
      Type.Literal('addRowBefore'), Type.Literal('addRowAfter'), Type.Literal('deleteRow'),
      Type.Literal('addColumnBefore'), Type.Literal('addColumnAfter'), Type.Literal('deleteColumn'),
      Type.Literal('deleteTable'), Type.Literal('alignLeft'), Type.Literal('alignCenter'),
      Type.Literal('alignRight'), Type.Literal('alignNone'), Type.Literal('moveRowUp'),
      Type.Literal('moveRowDown'), Type.Literal('moveColumnLeft'), Type.Literal('moveColumnRight'),
    ]),
  }, { additionalProperties: false, description: 'Apply an editor table command at cellId; use the containing table block\'s subtreeHash.' }),
]);

// Keep an object at the schema root for tool providers and parameter discovery.
// The alternatives require exactly one public edit form, including its local guards.
export const agentEditFileParameters = Type.Object({
  path: Type.String({ description: 'Absolute path or workspace-relative path.' }),
  oldText: Type.Optional(Type.String({ description: 'Exact text to replace. Must occur exactly once by default, match expectedOccurrences, or use replaceAll.' })),
  newText: Type.Optional(Type.String({ description: 'Replacement text.' })),
  expectedOccurrences: Type.Optional(Type.Integer({ minimum: 1, description: 'Exact number of expected oldText matches. Defaults to 1.' })),
  replaceAll: Type.Optional(Type.Boolean({ description: 'Replace every matching non-overlapping occurrence. Cannot be true with expectedOccurrences.' })),
  expectedSha256: Type.Optional(Type.String({ description: 'Required for ordinary exact edits of shared files. Optional additional whole-document guard for structured or block-targeted edits; their local guards allow unrelated user edits.' })),
  blockId: Type.Optional(blockId),
  document: Type.Optional(documentReference),
  operations: Type.Optional(Type.Array(structuredOperation, { minItems: 1, maxItems: 32,
    description: 'Structured block edits for a tiptap_blocks live document. Use instead of oldText/newText and include document from a structure read.' })),
}, {
  additionalProperties: false,
  anyOf: [
    { required: ['oldText', 'newText'], not: { anyOf: [{ required: ['operations'] }, { required: ['blockId'] }, { required: ['document'] }] } },
    { required: ['oldText', 'newText', 'blockId', 'document'], not: { required: ['operations'] } },
    { required: ['operations', 'document'], not: { anyOf:
      ['oldText', 'newText', 'blockId', 'expectedOccurrences', 'replaceAll'].map((key) => ({ required: [key] })) } },
  ],
});
